### ISSUE TITLE
Workaround kubernetes / zookeeper gaps

### ISSUE THREAD

**Issue by iocanel** [fabric8io/fabric8-zookeeper-docker#1]
ZooKeeper assumes that for each zookeeper server the election and the peer port use the same host ip.
On the other hand later versions of kubernetes use dedicated internal ip per service.

So the current image is not usable under later kubernetes versions.

It would be awesome if we could have a workaround this limitation until https://github.com/GoogleCloudPlatform/kubernetes/issues/1802 is resolved.

The easiest workaround would be to use port mapping of local ports to the actual server ports.

**Comment by mulloymorrow** [comment]
+1

**Comment by iocanel** [comment]
fwiw, the issue has been solved by using socat so that peer service host and election service host, can be unified under localhost, which pretty much solves the problem.
